"""lnSwitchboard backend package."""

from __future__ import annotations

import os


# LND's autogenerated TLS certificate is ECDSA. Python gRPC/BoringSSL can fail
# handshakes against that cert unless ECDSA cipher suites are explicitly enabled.
os.environ.setdefault("GRPC_SSL_CIPHER_SUITES", "HIGH+ECDSA")
